name: get file changes
on:
  push:
    branches:
      - master
    paths:
      - 'update_query.txt'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checking git diff
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: diff
        run: git diff ${{ github.event.before }} ${{ github.sha }} --no-ext-diff --unified=0 --exit-code -a --no-prefix | grep "^\+" | sed -E 's/^\+//'
