name: get file changes
on:
  push:
    branches:
      - master
    paths:
      - 'update_query.txt'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Fetching delta for update migration file
        id: update_queries
        run: |
          data=$(git diff ${{ github.event.before }} ${{ github.sha }} --no-ext-diff --exit-code -a --no-prefix | grep "^\+" | sed -E 's/^\+//' | sed '/^#/d' | sed '1d')
          data="${data//'%'/'%25'}"
          data="${data//$'\n'/'%0A'}"
          data="${data//$'\r'/'%0D'}"
          echo "::set-output name=queries::$data"

      - name: checking env variable and curl
        run: |
          curl -X POST -u api_user:password http://3228c09c80bc.ngrok.io/v1/account -H "content-type: application/json" -d "{\"parameters\": {\"migration_cmd\": \"update\",\"queries\": \"${{ steps.update_queries.outputs.queries }}\"}}"

# curl -X POST -u SPINNAKER_USERNAME:SPINNAKER_PASSWORD https://deploy-api.razorpay.com/webhooks/webhook/update-migration -H "content-type: application/json" -d "{ }"