name: get file changes
on:
  push:
    branches:
      - master
    paths:
      - 'update_query.txt'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checking git diff
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: diff
        run: git diff HEAD^ HEAD
